<a href="https://colab.research.google.com/github/nithishk20/Machine-Learning/blob/main/ML_ques2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
d=pd.read_csv('/content/patient_data.csv')
d

Age  Gender  Ethnicity  BMI  Blood Pressure (systolic)  \
0    45    Male  Caucasian   23                        120   
1    30  Female   Hispanic   27                        135   
2    65    Male    African   32                        150   
3    50  Female  Caucasian   29                        140   
4    28    Male      Asian   25                        115   
5    60  Female    African   35                        170   
6    40    Male   Hispanic   26                        130   
7    35  Female      Asian   24                        118   
8    55    Male  Caucasian   31                        142   
9    75  Female   Hispanic   26                        130   
10   48    Male    African   33                        160   
11   27  Female  Caucasian   22                        110   
12   58    Male      Asian   30                        135   
13   32    Male      Asian   22                        120   
14   45  Female      Black   28                        136   
15   58    Male      White   34                        150   
16   72  Female   Hispanic   26                        128   
17   41    Male      Black   30                        142   
18   45    Male      Asian   24                        120   
19   65  Female  Caucasian   28                        140   
20   30    Male    African   32                        130   
21   58  Female   Hispanic   26                        125   

    Blood Pressure (diastolic)  Heart Rate  Respiratory Rate  \
0                           80          75                16   
1                           90          80                18   
2                          100          90                20   
3                           95          70                14   
4                           75          80                16   
5                          110          85                18   
6                           85          75                16   
7                           78          70                14   
8                           95          80                16   
9                           85          80                20   
10                         100          90                20   
11                          72          75                14   
12                          90          75                16   
13                          80          75                16   
14                          92          80                18   
15                         100          70                20   
16                          84          85                14   
17                          94          77                16   
18                          80          70                16   
19                          90          80                20   
20                          85          85                18   
21                          80          75                16   

    Oxygen Saturation Level Chronic Conditions     Medications  \
0                        98               None            None   
1                        95       Hypertension            None   
2                        92           Diabetes         Insulin   
3                        96               None  Blood thinners   
4                        97               None            None   
5                        90       Hypertension            None   
6                        98               None            None   
7                        96               None            None   
8                        94      Heart Disease            None   
9                        92               None            None   
10                       92           Diabetes         Insulin   
11                       96               None            None   
12                       94               None            None   
13                       98               None            None   
14                       95       Hypertension            None   
15                       90           Diabetes  

In [2]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Age                         22 non-null     int64 
 1   Gender                      22 non-null     object
 2   Ethnicity                   22 non-null     object
 3   BMI                         22 non-null     int64 
 4   Blood Pressure (systolic)   22 non-null     int64 
 5   Blood Pressure (diastolic)  22 non-null     int64 
 6   Heart Rate                  22 non-null     int64 
 7   Respiratory Rate            22 non-null     int64 
 8   Oxygen Saturation Level     22 non-null     int64 
 9   Chronic Conditions          22 non-null     object
 10  Medications                 22 non-null     object
 11  Lab Test Results            22 non-null     object
 12  Chief Complaint             22 non-null     object
 13  Severity                    22 non-null     object
d

In [4]:
d.columns=d.columns.str.replace(' ','_')
d.columns

Index(['Age', 'Gender', 'Ethnicity', 'BMI', 'Blood_Pressure_(systolic)',
       'Blood_Pressure_(diastolic)', 'Heart_Rate', 'Respiratory_Rate',
       'Oxygen_Saturation_Level', 'Chronic_Conditions', 'Medications',
       'Lab_Test_Results', 'Chief_Complaint', 'Severity'],
      dtype='object')

In [6]:
d.describe()

Age        BMI  Blood_Pressure_(systolic)  \
count  22.000000  22.000000                  22.000000   
mean   48.272727  27.863636                 133.909091   
std    14.528074   3.870468                  14.857767   
min    27.000000  22.000000                 110.000000   
25%    36.250000  25.250000                 121.250000   
50%    46.500000  27.500000                 132.500000   
75%    58.000000  30.750000                 141.500000   
max    75.000000  35.000000                 170.000000   

       Blood_Pressure_(diastolic)  Heart_Rate  Respiratory_Rate  \
count                   22.000000   22.000000         22.000000   
mean                    88.181818   78.272727         16.909091   
std                      9.515083    6.048863          2.113654   
min                     72.000000   70.000000         14.000000   
25%                     80.000000   75.000000         16.000000   
50%                     87.500000   78.500000         16.000000   
75%                     94.750000   80.000000         18.000000   
max                    110.000000   90.000000         20.000000   

       Oxygen_Saturation_Level  
count                22.000000  
mean                 95.090909  
std                   2.505405  
min                  90.000000  
25%                  94.000000  
50%                  96.000000  
75%                  97.000000  
max                  98.000000

In [7]:
df=d.select_dtypes(exclude=['object'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         22 non-null     int64
 1   BMI                         22 non-null     int64
 2   Blood_Pressure_(systolic)   22 non-null     int64
 3   Blood_Pressure_(diastolic)  22 non-null     int64
 4   Heart_Rate                  22 non-null     int64
 5   Respiratory_Rate            22 non-null     int64
 6   Oxygen_Saturation_Level     22 non-null     int64
dtypes: int64(7)
memory usage: 1.3 KB


In [9]:
# Import label encoder
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
lc = preprocessing.LabelEncoder()
d['Severity']= lc.fit_transform(d['Severity'])
d['Severity'].unique()

array([2, 1, 0])

In [10]:
x=df
y=d['Severity']

In [11]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(x,y,test_size=0.2, random_state=11)

In [12]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(x_tr,y_tr)

SVC()

In [13]:
predict=model.predict(x_ts)

In [14]:
from sklearn import metrics
metrics.mean_absolute_error(y_ts,predict)

0.8

In [15]:
metrics.mean_squared_error(y_ts,predict)

1.2

In [16]:
import numpy as np
rmse=np.sqrt(metrics.mean_squared_error(y_ts,predict))
print(rmse)

1.0954451150103321


In [17]:
from sklearn.metrics import classification_report , confusion_matrix
print(classification_report(y_ts,predict))
print(confusion_matrix(y_ts,predict))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.33      1.00      0.50         1
           2       0.00      0.00      0.00         3

    accuracy                           0.40         5
   macro avg       0.28      0.67      0.39         5
weighted avg       0.17      0.40      0.23         5

[[1 0 0]
 [0 1 0]
 [1 2 0]]


/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
from sklearn import preprocessing
df1=df.copy()
#scaler=preprocessing.MinMaxScaler()->default feature_range=(0,1)
scalar=preprocessing.MinMaxScaler(feature_range=(0,1))
df1.iloc[:,:]=scalar.fit_transform(df)

In [19]:
x=df1
y=d['Severity']

In [20]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(x,y,test_size=0.2, random_state=5)

In [21]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(x_tr,y_tr)

SVC()

In [22]:
predict=model.predict(x_ts)

In [23]:
from sklearn import metrics
metrics.mean_absolute_error(y_ts,predict)

0.2

In [24]:
metrics.mean_squared_error(y_ts,predict)

0.2

In [25]:
import numpy as np
rmse=np.sqrt(metrics.mean_squared_error(y_ts,predict))
print(rmse)

0.4472135954999579


In [26]:
from sklearn.metrics import classification_report , confusion_matrix
print(classification_report(y_ts,predict))
print(confusion_matrix(y_ts,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      0.50      0.67         2
           2       0.67      1.00      0.80         2

    accuracy                           0.80         5
   macro avg       0.89      0.83      0.82         5
weighted avg       0.87      0.80      0.79         5

[[1 0 0]
 [0 1 1]
 [0 0 2]]
